[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300

[deploy.envs]
DATABASE_URL = "${RAILWAY_DATABASE_URL}"
MYSQLUSER = "${RAILWAY_USER}"
MYSQLPASSWORD = "${RAILWAY_PASSWORD}"
DATABASE_HOST = "${RAILWAY_TCP_PROXY_HOST}"
DATABASE_PORT = "${RAILWAY_TCP_PROXY_PORT}"
MYSQL_DATABASE = "astroturf"